#!/bin/sh
source sys-config

# install homebrew (and more importantly, wget, used by a lot of the app installation
# scripts)
source installers/homebrew
source installers/from-homebrew

source installers/chrome
source installers/deja-vu-font
source installers/iterm2
source installers/my-osx-dotfiles
source installers/adium

source generate/new-ssh-key
