#!/bin/sh
source sys-config

# install homebrew (and more importantly, wget, used by a lot of the app installation
# scripts)
source install/homebrew
source install/from-homebrew

source install/chrome
source install/deja-vu-font
source install/iterm2
source install/my-osx-dotfiles
source install/adium

source generate/new-ssh-key
