#!/bin/sh

brew install exiftool
brew install exiv2
brew install go
brew install hg
brew install imagemagick
brew install nvm
brew install postgresql
brew install qt
brew install rbenv
brew install redis
brew install ruby-build
brew install tmux
brew install ufraw
brew install vim
brew install wget

brew cask install spotify
brew cask install firefox
brew cask install google-chrome
brew cask install iterm2
brew cask install vlc
brew cask install 1password
brew cask install slack
