#!/bin/sh
brew install wget
brew install tmux
brew install node
brew install rbenv
brew install ruby-build
brew install vim
brew install exiftool
brew install postgresql
brew install imagemagick
brew install ufraw
