#!/usr/bin/env bash
git clone https://github.com/clalimarmo/dotfiles.git ~/dotfiles
ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/.gitignore_global ~/
ln -sf ~/dotfiles/.vim ~/
ln -sf ~/dotfiles/.vimrc ~/
ln -sf ~/dotfiles/osx/.bash_profile ~/
ln -sf ~/dotfiles/osx/.tmux.conf ~/
