#!/bin/sh

# Credit to https://github.com/mathiasbynens/dotfiles

echo configuring laptop system...

# SSD Specific Settings:

# Enable hibernation (hibernate when I run out of power)
# sudo pmset -a hibernatemode 1
# Disable hibernation (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

# Disable the sudden motion sensor as it’s not useful for SSDs
sudo pmset -a sms 0

echo done
